version: '3.8'

services:
  backend:
    build: backend/
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./backend/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ${DATABASE_NAME}" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

  python-service:
    build:
      context: .
      dockerfile: backend/external/python-service/Dockerfile
    container_name: python-service
    ports:
      - "8000:8000"
    networks:
      - internal

networks:
  internal:
    driver: bridge
